Nuclear-Squid/ergol

Makefile
The Makefile used to build and install QWERTY-Lafayette. This should fix it.
=> Made so the Makefile installs ergol and not lafayette

css/demo.css
This should hopefully resolve #60. Sadly we can’t use green (as suggested) since that color is used by the upcoming PR #61 when we fix a typo. I used slightly different shades of gray, which I think is enough but I’m not quite sure. Here’s a before and after comparison :
Before :
After :
=> [dactylo] Improve contrast on light theme.

README.md
Hello,
First of all, thanks for your great work the ergo‑L team!
Now, about this PR: I added some documentations in the `README` file:
- how to edit the different corpora and use the scripts in the `data/corpus` directory;
- how to easily run a local server using python `http.server`: <https://docs.python.org/3.12/library/http.server.html>.
You can obviously edit the PR as you see fit, such as moving the part about the corpora in `data/corpus/README.md` for example if you don’t want to have it in the repository `README.md`.
Regards,
– Chouhartem
=> README additions: corpora and http.server

www/content/lafayette.md
This PR proposes the following two changes:
- Add a table of contents in the “Lafayette*” page (their description can be edited as you see fit);
- Fix a couple of typos in the aforementioned page.
=> Add a table of contents in the Lafayette* page.

www/content/bepo/index.md, www/content/comparatif/index.md, www/content/lts/index.md
I’d like to use some colspan for the header but sadly, I can’t even get [this pandoc example](https://pandoc.org/chunkedhtml-demo/8.9-tables.html) to work:
```md
+---------------------+-----------------------+
| Location            | Temperature 1961-1990 |
|                     | in degree Celsius     |
|                     +-------+-------+-------+
|                     | min   | mean  | max   |
+=====================+=======+=======+=======+
| Antarctica          | -89.2 | N/A   | 19.8  |
+---------------------+-------+-------+-------+
| Earth               | -89.2 | 14    | 56.7  |
+---------------------+-------+-------+-------+
```
=> minor fixes (/comparatif)

code/keebs.js, www/layouts/shortcodes/x-keyboard.html, www/static/img/lafayette.svg
This isolates the stylesheets and lets us access the SVG document without having to load it twice.
=> using <object> rather than <img> for keebs

www/assets/css/theme.css
`<a>` tags may also be used as anchors, so target only tags with `href` attributes to style links.
=> css: Fix anchors styling

www/content/lexique.md
Quelques modifications mineures pour soigner la présentation du lexique : 
- paragraphes imbriqués dans les `<dd>` plutôt que des retours à la ligne
- liste imbriquée dans un `<dd>`
- éviter le décalage introduit par les éléments `<sup>`
- contournement d’un défaut de support des diacritiques combinants par Pandoc
À fusionner après #124.
@wismill ça te convient ?
=> Lexique (style / présentation)

www/assets/css/theme.css, www/content/erglace.md, www/content/lexique.md, www/layouts/partials/footer.html, www/layouts/partials/header.html
- main title a bit lower
- subtitle centered
- lighter navlink separators
before : 
after : 
@cedricr r?
=> centered subtitle + lighter navbars

www/content/alternatives/index.md, www/content/bepo/index.md, www/content/lafayette.md, www/content/presentation/index.md
Il semble y avoir plusieurs conventions utilisées pour se référer aux couches et aux touches associées. Ce serait bien d’avoir une convention de nommage et typographique pour plus de clarité.
Cette PR vise à démarrer la discussion. Lorsque les conventions seront établies, il faudra ensuite s’assurer de les appliquer sur tout le site.
=> Convention typographique pour les couches et touches associées

www/content/stats.html
I had to specify `input[placeholder]` in a previous PR so that `querySelector` doesn’t target the radio buttons that we now use to pick a geometry in other pages. And forgot this could break the /stats page because I’m an idiot and we have no unit tests.
=> [bugfix] /stats: re-enable layout emulation

www/content/bepo/index.md
This PR fixes some missing images:
- Regression from 95744c324f1ad3c87d19cda7d0e5462d2bcf07ec
- Similar to 5f075cb59a66033dfb7e5edc1ee01fb5a8bdf9bd
=> Fix missing images in the bépo presentation page

www/layouts/shortcodes/layout-list.html
J’ai supprimé la version dev étant donné qu’elle a été remplacée par la v1 ;)
=> Suppression de Ergo-L(dev) dans la page Analyseur

www/content/articles/ergol_sous_swaywm.md, www/data/authors/steeve.toml
Juste un petit article décrivant la configuration Ergo-L sous Sway.
Je ne connais pas trop Hugo, j’ai essayé de m’aligner sur le format des autres articles.
=> Ajout d’un article: Configurer un clavier en Ergo-L sous SwayWM

README.md
Ergol is available in Debian unstable, and should become available in Ubuntu soon.
=> README: mention that Ergol is available in debian

www/content/installation/index.md
This fixes the submenu and uses `<h3>` headings rather than a definition list, which was semantically incorrect and difficult to deal with in Markdown.
=> Mention xkb-config 2.42+ in the "installation" page

www/content/ressources/faq.md
Le bug de Firefox qui empêchait le chaînage de touches mortes a été corrigé dans la version 131 (merci à Xiloynaha pour le test).
=> Ajout de la version de FF qui corrige le chaînage de touches mortes.

www/content/ressources/glossaire.md
The `^` key is not displayed properly on https://ergol.org/ressources/glossaire/ because it's a special character so it must be escaped.
=> fix: doc: fix '^' rendering as key pressed

www/content/articles/analyse_et_optimisation/index.md
La disposition a été renommée d’HyperTexte➜Ergopti, le lien du site a donc changé
=> Mise à jour du lien du site Ergopti

www/content/installation/index.md
Astuce pour mettre Ergo‑L en disposition clavier par défaut sur Windows.
=> website: astuces installation

.github/workflows/hugo.yaml
L’erreur: https://github.com/Nuclear-Squid/ergol/actions/runs/13383923801/job/37377150480#step:1:29
Il faut mettre à jour [`actions/upload-pages-artifact`](https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0), ce qui nécessite aussi de mettre à jour [`actions/deploy-pages`](https://github.com/actions/deploy-pages/releases/tag/v4.0.0). Il semblerait qu’il suffise de mettre à jour les numéros de version sans autres changements.
=> website: fix deployment by updating GitHub

www/content/ressources/faq.md
Appliquer les changements dans ~/.profile ne fonctionne pas sur Ubuntu 24.04. En revanche, la solution mentionnée dans #177¹ qui consiste à modifier /etc/environment fonctionne.
¹: https://github.com/Nuclear-Squid/ergol/issues/177
=> Supprime référence à ~/.profile dans la FAQ Linux
