- index.html
Il y a @fabi1cazenave qui causait sur un réseau social et j'ai été voir le site pour me cultiver :) j'en ai profité pour passer l'excellent Grammalecte sur la page et faire un petit commit ici.
<aside>Bravo pour le travail sur le sujet, est-ce que je vais enfin me décider à apprendre un layout décent...</aside>
> Quelques coquilles de nitpiqueur de mouche

- README.md
Add some instructions to install ErgoL (or whatever layout) on Arch Linux XOrg
> Add Arch install guide in the README

- .prettierignore
- .prettierrc
- css/heatmap.css
- css/layout.css
- index.html
- js/collapsable-table.js
- js/demo.js
- js/heatmap.js
- js/x-keyboard.js
- stats.html
As you advised, @fabi1cazenave, I ran prettier on most of the code base. I mostly kept the default settings (aside from using single quotes instead of double quotes, and removing brackets from arrow functions, when possible). I didn’t push directly onto `new_stats_page` branch in case I made a mistake (or if you don’t agree with the choices I or prettier made)
> Ran 'prettier' with mostly default settings.

- fortunes.md
Une pratique que les moins de ~~20 ans~~ 40 ans ne peuvent pas connaître… mais qui m’amusait beaucoup à l’époque, et qui permettrait de garder trace des meilleures citations concernant Ergo‑L ou les projets concurrents. Ça pourrait finir en témoignages sur le site web. :-)
L’idée serait évidemment qu’à chaque citation pertinente ou amusante on fasse une PR pour compléter ce fichier. Ça permettrait à des contributeurs moins techniques de figurer en collaborateurs sur le dépôt git.
> project fortunes

- README.md
Just adding a mention to the AUR package in the `README.md` file and fix a typo.
> Add mention to the AUR package in the readme

- css/demo.css
- js/dactylo.js
Display a cursor under the current char + turn the char in red on an error + turn the char in green when the error is fixed.
> [dactylo] show a cursor under the current char

- Makefile
Hi,
A fix proposal for issue #77.
The goal is to follow recent changes in kalamine
- https://github.com/OneDeadKey/kalamine/issues/97
- https://github.com/OneDeadKey/kalamine/pull/129
> `kalamine make` → `kalamine build` (#77)

- www/content/bepo/index.md
Quelques typos relevées dans #85.
– Chouhartem
> qwerty: quelques éléments de relecture

- README.md
Hello,
This PR proposes the following changes:
1. Update the outdated section about `http.server`
2. Fix a couple of typos
Best,
– Chouhartem
> readme: Update to include hugo server

- code/keebs.js
- www/assets/css/heatmap.css
- www/content/stats.html
> stats: quickfix + better warning

- code/keebs.js
Ooops. Quick regression fix after #106.
> quick fix: geometry selector

- www/assets/css/theme.css
- www/layouts/partials/head.html
- www/static/img/bepo.svg
- www/static/img/bepolar.svg
- www/static/img/colemak-french-touch.svg
- www/static/img/erglace.svg
- www/static/img/ergol.svg
- www/static/img/lafayette.svg
> Dark reader

- code/keebs.js
- www/content/_index.md
- www/content/bepo/index.md
- www/content/erglace.md
- www/content/lafayette.md
- www/content/stats.html
- www/layouts/shortcodes/x-keyboard.html
- www/static/favicon.svg
- www/static/img/bepo.svg
> better Bépo SVG display

- www/content/lexique.md
- www/layouts/partials/header.html
WIP, but feel free to comment.
> Lexique: improve Linux section

- www/assets/css/keebs.css
- www/assets/css/theme.css
- www/content/dactylo/index.html
- www/content/lexique.md
- www/layouts/shortcodes/x-keyboard.html
@cedricr r?
Just a quickfix for tonight. I know a better layout is needed — and not only for mobile.
> better mobile layout

- www/content/lafayette.md
> Fix typos on Lafayette page.

- www/content/_index.md
- www/content/bepo/index.md
- www/content/comparatif/index.md
« se mesure mieux plus à son pire défaut », finalement, c’était pas ouf comme phrase
> [www] comparatif : reformulation

- code/duck-typist.js
A proposal to add progress bar on the status message to better visualize the threshold.
> Add progress bar on status message

- www/assets/css/theme.css
- www/content/dactylo/index.html
- www/hugo.toml
- www/layouts/404.html
- www/layouts/_default/baseof.html
Looks like I’ve degraded our beloved 404 page with #142. Here’s a fix.
> [www] make 404 great again

- www/content/glossaire.md
- www/content/stats.html
- www/hugo.toml
> feat(website): Rename “lexique” to “glossaire”

- www/content/lts/index.md
> Update index.md de LTS

- www/content/alternatives/index.md
Petites corrections à la con aussi.
> Update index.md de alternatives

- www/content/bepo/index.md
Corrections de texte diverses.
> Update index.md Bepo

- README.md
I added a paragraph in the readme about a configuration that solves problems with some apps on ubuntu / wayland.
> doc about troubleshooting with ubuntu - wayland

- README.md
Following 95744c324f1ad3c87d19cda7d0e5462d2bcf07ec
> Correct links to images in README

- www/content/articles/ergol_1_0_0.md
Hello,
In this PR, there are some grammatical checks on the page for some typos I noticed.
> Annonce ergo‑L : relecture

- www/content/articles/ergol_1_0_0.md
si l’on en croit https://github.com/Nuclear-Squid/ergol/commits/main/www/content/articles/ergol_1_0_0.md
> date de publication réelle

- www/content/alternatives/index.md
There is a broken link for the bépolar layout on alternatives page
> Fix bépolar broken link

- www/content/articles/apprendre_a_taper/index.md
Corrections mineures d’orthographe et de typographie sur le dernier article.
> orthographe

- www/assets/css/theme.css
> prevent img from overflowing

- www/assets/css/theme.css
> limit image width in desktop mode

- code/duck-typist.js
Hey,
Thanks for the layout! I'm learning it using the website and I found that the new letters are not always included in the lesson words. I feel that it slows down the learning, so here's my contribution.
Cheers,
> duck-typer: include new letters in each words

- layouts/colemak-french-touch.toml
- www/content/alternatives/lafayette/index.md
- www/content/articles/ergol_1_0_0.md
Déplacement du dépot CFT vers Codeberg
> Goodbye GAFAMs

- www/content/articles/analyse_et_optimisation/index.md
Je peaufine l’intro vite fait, j’espère que personne ne m’en voudra ?
> analyet et optimisation : intro

- www/layouts/_default/single.html
> auteur en haut d’article

- www/layouts/_default/home.html
- www/layouts/_default/list.html
> plus de visibilité aux auteurs et autrices

- CODE_OF_CONDUCT.md
Ces deux points médians semblent être inutile de l’avis général.
> CODE_OF_CONDUCT.md: suppression de 2 points médians

- www/layouts/partials/footer.html
Add link to Mastodon account with verification attributes
> Add Mastodon verification link

- www/content/alternatives/hypergol/index.md
Merci pour la lecture, voici quelques propositions d’amélioration mineures. 🙂
> Hypergol: fix typos and add links
